- name: Ensure ansible_facts used by role
  ansible.builtin.setup:
    gather_subset: min
  when: __postgresql_required_facts | difference(ansible_facts.keys() | list) | length > 0

- name: Set platform/version specific variables
  ansible.builtin.include_vars: "{{ __postgresql_vars_file }}"
  loop:
    - "{{ ansible_facts['distribution'] }}_{{ ansible_facts['distribution_version'] }}.yml"
    - "{{ ansible_facts['os_family'] }}_{{ ansible_facts['distribution_version'] }}.yml"
    - "{{ ansible_facts['distribution'] }}_{{ ansible_facts['distribution_major_version'] }}.yml"
    - "{{ ansible_facts['os_family'] }}_{{ ansible_facts['distribution_major_version'] }}.yml"
    - "{{ ansible_facts['distribution'] }}.yml"
    - "{{ ansible_facts['os_family'] }}.yml"
  vars:
    __postgresql_vars_file: "{{ role_path }}/vars/{{ item }}"
  when: __postgresql_vars_file is file
