__postgresql_bin_dir: /usr/pgsql-{{ postgresql_version }}/bin
__postgresql_data_dir: /var/lib/pgsql/{{ postgresql_version }}/data/
__postgresql_config_dir: /var/lib/pgsql/{{ postgresql_version }}/data/

__postgresql_service_name: postgresql-{{ postgresql_version }}
