galaxy_info:
  author: Damian Morgan
  description: Role to install and configure PostgreSQL
  license: PostgreSQL
  min_ansible_version: "2.15"

  # If this a Container Enabled role, provide the minimum Ansible Container version.
  # min_ansible_container_version:

  galaxy_tags:
    - database
    - postgresql

dependencies: []
