---
postgresql_version: 18

postgresql_authentication_records:
    # "local" is for Unix domain socket connections only
  - { type: local, databases: [all], users: [all], method: trust }
    # IPv4 local connections:
  - { type: host, databases: [all], users: [all], address: 127.0.0.1/32, method: trust}
    # IPv6 local connections:
  - { type: host, databases: [all], users: [all], address: "::1/128", method: trust}
    # Allow replication connections from localhost, by a user with the
    # replication privilege.
  - { type: local, databases: [replication], users: [all], method: trust}
  - { type: host, databases: [replication], users: [all], address: 127.0.0.1/32, method: trust}
  - { type: host, databases: [replication], users: [all], address: "::1/128", method: trust}

postgresql_listen_addresses: [localhost]
postgresql_port: 5432
postgresql_max_connections: 100
postgresql_reserved_connections: 0
postgresql_superuser_reserved_connections: 3
postgresql_unix_socket_directories: ["/run/postgresql"]
postgresql_unix_socket_group: ""
postgresql_unix_socket_permissions: "0777"
postgresql_bonjour: false
postgresql_bonjour_name: ""
postgresql_tcp_keepalives_idle: 0
postgresql_tcp_keepalives_interval: 0
postgresql_tcp_keepalives_count: 0
postgresql_tcp_user_timeout: 0
postgresql_client_connection_check_interval: 0

postgresql_authentication_timeout: 1min
postgresql_password_encryption: scram-sha-256
postgresql_scram_iterations: 4096
postgresql_md5_password_warnings: true
postgresql_krb_server_keyfile: FILE:${sysconfdir}/krb5.keytab
postgresql_krb_caseins_users: false
postgresql_gss_accept_delegation: false
postgresql_oauth_validator_libraries: ""

postgresql_ssl: false
postgresql_ssl_ca_file: ""
postgresql_ssl_cert_file: server.crt
postgresql_ssl_crl_file: ""
postgresql_ssl_crl_dir: ""
postgresql_ssl_key_file: server.key
postgresql_ssl_tls13_ciphers: []
postgresql_ssl_ciphers: ["HIGH", "MEDIUM", "+3DES", "!aNULL"]
postgresql_ssl_prefer_server_ciphers: true
postgresql_ssl_groups: ["X25519", "prime256v1"]
postgresql_ssl_min_protocol_version: TLSv1.2
postgresql_ssl_max_protocol_version: ""
postgresql_ssl_dh_params_file: ""
postgresql_ssl_passphrase_command: ""
postgresql_ssl_passphrase_command_supports_reload: false

postgresql_shared_buffers: 128MB
postgresql_huge_pages: try
postgresql_huge_page_size: "0"
postgresql_temp_buffers: 8MB
postgresql_max_prepared_transactions: 0
postgresql_work_mem: 4MB
postgresql_hash_mem_multiplier: 2.0
postgresql_maintenance_work_mem: 64MB
postgresql_autovacuum_work_mem: "-1"
postgresql_vacuum_buffer_usage_limit: 2MB
postgresql_logical_decoding_work_mem: 64MB
postgresql_commit_timestamp_buffers: "0"
postgresql_multixact_member_buffers: "32"
postgresql_multixact_offset_buffers: "16"
postgresql_notify_buffers: "16"
postgresql_serializable_buffers: "32"
postgresql_subtransaction_buffers: "0"
postgresql_transaction_buffers: "0"
postgresql_max_stack_depth: 2MB
postgresql_shared_memory_type: mmap
postgresql_dynamic_shared_memory_type: posix
postgresql_min_dynamic_shared_memory: "0"

postgresql_temp_file_limit: "-1"
postgresql_file_copy_method: copy
postgresql_file_extend_method: posix_fallocate
postgresql_max_notify_queue_pages: 1048576
