---
postgresql_version: 18

postgresql_authentication_records:
    # "local" is for Unix domain socket connections only
  - { type: local, databases: [all], users: [all], method: trust }
    # IPv4 local connections:
  - { type: host, databases: [all], users: [all], address: 127.0.0.1/32, method: trust}
    # IPv6 local connections:
  - { type: host, databases: [all], users: [all], address: "::1/128", method: trust}
    # Allow replication connections from localhost, by a user with the
    # replication privilege.
  - { type: local, databases: [replication], users: [all], method: trust}
  - { type: host, databases: [replication], users: [all], address: 127.0.0.1/32, method: trust}
  - { type: host, databases: [replication], users: [all], address: "::1/128", method: trust}

postgresql_max_connections: 100
postgresql_shared_buffers: 128MB
postgresql_dynamic_shared_memory_type: posix
